name: dj_bean_manor_water&dj_fruit_collect

on:
    workflow_dispatch:
    schedule:
        - cron: "40 */1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: dj_bean_manor_water&dj_fruit_collect

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: 'Set up Python'
            uses: actions/setup-python@v1
            with:
              python-version: 3.7

          - name: 'Install requirements'
            run: pip install -r ./requirements.txt
            
                  
          - name: run
            run: |             
             sed -i -e '/pt/d' ./config.yaml
             sed -i "15c${{ secrets.TEST_COOKIE }}" ./config.yaml
             sed 's/&/\n/g' ./config.yaml
             sed -i "/pt/s/^/  - /g" ./config.yaml
             sed -i "s/aaa/${{ secrets.TG_BOT_TOKEN }}/g" ./config.yaml
             sed -i "s/bbb/${{ secrets.TG_USER_ID }}/g" ./config.yaml
             sed -i "s/weixin/${{ secrets.WECHAT_WORK }}/g" ./config.yaml
             sed -i "s/default=0/default=1/g" ./db/model.py
             mkdir conf 
             mv ./config.yaml ./conf/config.yaml        
             
             python3 dj_bean_manor_water.py
             python3 dj_fruit_collect.py
                  
