name: dj_fruit

on:
    workflow_dispatch:
    schedule:
        - cron: "10 16,19,0,3,9 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: dj_fruit

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: 'Set up Python'
            uses: actions/setup-python@v1
            with:
              python-version: 3.7

          - name: 'Install requirements'
            run: pip install -r ./requirements.txt
            
                  
          - name: run
            run: |             
             sed -i "15c/${{ secrets.JD_COOKIE1 }}" ./config.yaml
             sed -i "16c/${{ secrets.JD_COOKIE2 }}" ./config.yaml
             sed -i "17c/${{ secrets.JD_COOKIE3 }}" ./config.yaml
             sed -i "15,17s/^/  - /g" ./config.yaml
             sed -i "s/aaa/${{ secrets.TG_BOT_TOKEN }}/g" ./config.yaml
             sed -i "s/bbb/${{ secrets.TG_USER_ID }}/g" ./config.yaml
             mkdir conf 
             mv ./config.yaml ./conf/config.yaml        
             
             python3 dj_fruit.py
                  
